{% set name = "mbedtls" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ARMmbed/mbedtls/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bdee0e3e45bbf360541306cac0cc27e00402c7a46b9bdf2d24787d5107f008f2

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - mbedtls_hello

about:
  home: https://tls.mbed.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: An open source, portable, easy to use, readable and flexible SSL library

extra:
  recipe-maintainers:
    - izahn
    - notestaff
