{% set name = "mbedtls" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ARMmbed/mbedtls/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 113fa84bc3cf862d56e7be0a656806a5d02448215d1e22c98176b1c372345d33

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - mbedtls_hello

about:
  home: https://tls.mbed.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: An open source, portable, easy to use, readable and flexible SSL library

extra:
  recipe-maintainers:
    - izahn
