{% set name = "mbedtls" %}
{% set version = "3.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ARMmbed/mbedtls/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 597419f1a4a79dd28e6f5edc5180aff7e83bd85548437e07dcf9f808ceccb76

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - mbedtls_hello

about:
  home: https://tls.mbed.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: An open source, portable, easy to use, readable and flexible SSL library

extra:
  recipe-maintainers:
    - izahn
