schema_version: 1

context:
  name: mbedtls
  version: "4.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-${{ version }}/mbedtls-${{ version }}.tar.bz2
  sha256: 377a09cf8eb81b5fb2707045e5522d5489d3309fed5006c9874e60558fc81d10

build:
  number: 1

requirements:
  build:
    - cmake
    - if: not win
      then: make
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
  run_exports:
    - ${{ pin_subpackage('mbedtls', upper_bound='x.x') }}

tests:
  - package_contents:
      lib:
        - mbedcrypto
        - mbedtls
      include:
        - mbedtls/private/md5.h

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: An open source, portable, easy to use, readable and flexible SSL library
  homepage: https://tls.mbed.org/
  repository: https://github.com/Mbed-TLS/mbedtls

extra:
  recipe-maintainers:
    - izahn
    - carlodri
    - xhochy
