schema_version: 1

context:
  name: mbedtls
  version: "4.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-${{ version }}/mbedtls-${{ version }}.tar.bz2
  sha256: 2bed9d713b4668f76553b097e72b8aa30bc8f112a940d7ae228d524bbde6ffea

build:
  number: 0

requirements:
  build:
    - cmake
    - if: not win
      then: make
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
  run_exports:
    - ${{ pin_subpackage('mbedtls', upper_bound='x.x') }}

tests:
  - script:
      - if: win
        then:
          - if not exist %LIBRARY_BIN%\\libmbedcrypto.dll exit 1
          - if not exist %LIBRARY_LIB%\\libmbedcrypto.lib exit 1
          - if not exist %LIBRARY_LIB%\\mbedtls.lib exit 1
          - if not exist %LIBRARY_BIN%\\mbedtls.dll exit 1
      - if: linux
        then:
          - test -f ${PREFIX}/lib/libmbedcrypto.so
          - test -f ${PREFIX}/lib/libmbedtls.so
      - if: osx
        then:
          - test -f ${PREFIX}/lib/libmbedcrypto.dylib
          - test -f ${PREFIX}/lib/libmbedtls.dylib
  - package_contents:
      include:
        - mbedtls/private/md5.h

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: An open source, portable, easy to use, readable and flexible SSL library
  homepage: https://tls.mbed.org/
  repository: https://github.com/Mbed-TLS/mbedtls

extra:
  recipe-maintainers:
    - izahn
    - carlodri
    - xhochy
